package protocol

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

// GenerateConfig turns UI-supplied params into a config file and (optionally)
// a shareable URI. binPath is the resolved server binary path.
func GenerateConfig(p Protocol, binPath string, params map[string]string) (*ConfigResult, error) {
	// fill defaults
	for _, f := range p.Fields {
		if _, ok := params[f.Key]; !ok && f.Default != "" {
			params[f.Key] = f.Default
		}
	}

	// validate required
	for _, f := range p.Fields {
		if f.Required && strings.TrimSpace(params[f.Key]) == "" {
			return nil, fmt.Errorf("field %q is required", f.Label)
		}
	}

	switch p.ID {
	case "olcrtc":
		return genOlcRTC(params)
	case "openflux":
		return genOpenFlux(params)
	default:
		return nil, fmt.Errorf("no config generator for %s", p.ID)
	}
}

// --- olcRTC -----------------------------------------------------------------

func genOlcRTC(params map[string]string) (*ConfigResult, error) {
	key := strings.TrimSpace(params["key"])
	if key == "" {
		b := make([]byte, 32)
		_, _ = rand.Read(b)
		key = hex.EncodeToString(b)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "mode: srv\n")
	fmt.Fprintf(&b, "auth:\n")
	fmt.Fprintf(&b, "  provider: %q\n", params["provider"])
	if t := strings.TrimSpace(params["wb_token"]); t != "" {
		fmt.Fprintf(&b, "  token: %q\n", t)
	}
	fmt.Fprintf(&b, "room:\n")
	fmt.Fprintf(&b, "  id: %q\n", params["room"])
	fmt.Fprintf(&b, "crypto:\n")
	fmt.Fprintf(&b, "  key: %q\n", key)
	fmt.Fprintf(&b, "net:\n")
	dns := params["dns"]
	if dns == "" {
		dns = "8.8.8.8:53"
	}
	fmt.Fprintf(&b, "  transport: %q\n", params["transport"])
	fmt.Fprintf(&b, "  dns: %q\n", dns)
	fmt.Fprintf(&b, "debug: false\n")

	uri := fmt.Sprintf("olcrtc://%s?%s@%s#%s",
		params["provider"], params["transport"], params["room"], key)

	return &ConfigResult{Config: b.String(), URI: uri}, nil
}

// --- OpenFlux ---------------------------------------------------------------

func genOpenFlux(params map[string]string) (*ConfigResult, error) {
	mode := params["mode"]
	if mode == "" {
		mode = "l4"
	}
	codec := params["codec"]
	if codec == "" {
		codec = "batched"
	}

	args := []string{
		"--role=exit",
		"--mode=" + mode,
		"--transport=" + params["transport"],
		"--url=" + params["url"],
	}
	if codec != "batched" {
		args = append(args, "--codec="+codec)
	}
	if f := strings.TrimSpace(params["encryption_key_file"]); f != "" {
		args = append(args, "--encryption-key-file="+f)
	}
	if t := strings.TrimSpace(params["max_token"]); t != "" {
		args = append(args, "--maxToken="+t)
	}
	if u := strings.TrimSpace(params["max_uid"]); u != "" {
		args = append(args, "--maxUid="+u)
	}
	if params["debug"] == "true" {
		args = append(args, "--debug")
	}

	cmd := "./openflux " + strings.Join(args, " ")

	var b strings.Builder
	fmt.Fprintf(&b, "# OpenFlux exit node\n")
	fmt.Fprintf(&b, "# Generated by LaLune Panel\n")
	fmt.Fprintf(&b, "command: %s\n", cmd)
	fmt.Fprintf(&b, "mode: %s\n", mode)
	fmt.Fprintf(&b, "transport: %s\n", params["transport"])
	fmt.Fprintf(&b, "url: %s\n", params["url"])
	fmt.Fprintf(&b, "codec: %s\n", codec)

	return &ConfigResult{Config: b.String()}, nil
}
